=== elthariel/zia84/conf/zia_conf.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT zia (network, server)>
<!ELEMENT network (port, address+)>
  <!ELEMENT port (#PCDATA)>
  <!ELEMENT address (#PCDATA)>
<!ELEMENT server (name, root, cgi)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT root (#PCDATA)>
  <!ELEMENT cgi (#PCDATA)>

=== elthariel/zia84/conf/zia_default.xml
<?xml version="1.0"?>
<!DOCTYPE zia SYSTEM "zia_conf.dtd">
<zia>
  <network>
    <port>8080</port>
    <address>all</address>
  </network>
  <server>
    <name>www.test.com</name>
    <root>/var/www</root>
    <cgi>/var/www/cgi-bin</cgi>
  </server>
</zia>
